### ISSUE TITLE
Vimcom runs [R] console in hidden state in windows

### ISSUE THREAD

**Issue by hdarabi** [jalvesaq/VimCom#33]
Hi,

I had vimcom installed on my windows machine and I was using it successfully for my development. However, recently when I run the \rf command from vim it starts a new [R] window but it's hidden and when I click on the icon on taskbar nothing comes up. 

Thanks for your help
Hamid

**Comment by jalvesaq** [comment]
What are your versions of vim, vimcom, vim-r-plugin and windows?

**Comment by hdarabi** [comment]
Thanks Jackson for quick response. Here are the information

[R] version **3.2.3**
vim version** 7.4** (I use **gvim** on windows)
vimcom version **1.2-7.2**
vim-r-plugin **1.2.7**
Windows **7 Professional**

**Comment by jalvesaq** [comment]
Vim-R-plugin 1.2.7 = released version
vimcom 1.2-7.2 = development version

Did you get the Vim-R-plugin from github? I did not increased the version number... If there is no mismatch between Vim-R-plugin and vimcom versions, then, perhaps you could try to update Vim.

On http://www.vim.org/download.php there is a link for Vim "without Cream" which is a much more recent version of Vim than the last official release.

**Comment by hdarabi** [comment]
@jalvesaq I installed it from github since it was removed form Cran. I will try updating the vim version and check this again. Thanks

**Comment by hdarabi** [comment]
Ok, I confirm that I installed it from Github. The default version for vimcom is 1.2.7-2 when you install it by devtools::install_github("jalvesaq/VimCom"). I tried removing and installing package multiple times and the problem persists. I also tried the cream on vim download page but there was a complaint that vim version should be 7.4 and higher.

**Comment by jalvesaq** [comment]
I only really use Linux, and unfortunately I can't do as much tests on Windows as I do on Linux because I have to reboot the computer each time that I need to test the Vim-R-plugin on Windows. One feature recently included was that position and size of Vim and R windows are cached when you do \rq and are restored at \rf. If it happened that you issued the command \rq with R minimized, perhaps the registered size was zero. But this should be fixed the next time you executed the command \rq with R window not minimized.

**Comment by hdarabi** [comment]
Thanks Jackson,

I guess it solves the mystery. I use Ubuntu at home but at work I use windows. The problem persists with windows because the program is unable to maximize itself, that results in staying hidden. I'll try reverting to former versions if possible. Thanks for you kind help.

Yours,
Hamid

**Comment by jalvesaq** [comment]
If indeed this is the problem, you can solve it deleting the file `C:\Users\yourlogin\AppData\Roaming\Vim-R-plugin\win_pos`.

**Comment by jalvesaq** [comment]
I could confirm that the problem was caused by this feature, and I'm going to commit the fix now.

**Comment by jalvesaq** [comment]
Fixed by https://github.com/jalvesaq/VimCom/commit/297cb1d9e68e71c24c1e13234b710860306859e7

**Comment by hdarabi** [comment]
Thanks! I works like a charm now. Thanks for your awesome work and wonderful support.

Yours,
Hamid
